spring:
  datasource:
    password: 181091
    username: root
    url: jdbc:mysql://localhost:3306/fornecedor?useTimezone=true&serverTimezone=UTC
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
